// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

import * as HomeRoute from "@/app/page.info";
import * as SigninRoute from "@/app/(auth)/signin/page.info";
import * as SignupRoute from "@/app/(auth)/signup/page.info";
import * as DashboardRoute from "@/app/dashboard/page.info";

export const Home = makeRoute("/", {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const Signin = makeRoute("/(auth)/signin", {
  ...defaultInfo,
  ...SigninRoute.Route,
});
export const Signup = makeRoute("/(auth)/signup", {
  ...defaultInfo,
  ...SignupRoute.Route,
});
export const Dashboard = makeRoute("/dashboard", {
  ...defaultInfo,
  ...DashboardRoute.Route,
});
