import "../styles/globals.css";

import type { Metadata } from "next";

import Footer from "@/components/section/Footer";
import Header from "@/components/section/Header";
import { R, RI } from "@/styles/Fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${R.variable} ${RI.variable} container mx-auto antialiased`}
      >
        <Header />
        <div className="prose-base"> {children}</div>
        <Footer />
      </body>
    </html>
  );
}
