import "../styles/globals.css";

import type { Metadata } from "next";

import Footer from "@/components/section/Footer";
import Header from "@/components/section/Header";
import { R, RI } from "@/styles/Fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${R.variable} ${RI.variable} antialiased`}>
        <div className="grid h-screen grid-rows-[auto_1fr_auto]">
          <Header />
          <div className="container prose-base mx-auto py-3"> {children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
